In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
import numpy as np

In [7]:
from graph_envs.GraphEnv.impnode import ImpnodeEnv

seed = 5545

In [8]:
env = ImpnodeEnv(8,2,3,seed)
env.action_space.seed(seed)

[5545]

In [9]:
for i in range(1):
    terminated = False
    #num_nodes = env.num_nodes()
    mask = np.ones((env.num_nodes()), dtype=np.int8)
    print(mask)
    while terminated is False:
        print(env.observation_space.shape[0])
        print(env.action_space.n)
        action = env.action_space.sample(mask=mask)
        print(action)
        mask[action] = 0
        print(mask)
        observation, reward, terminated, truncated, info = env.step(action)
    env.reset()

[1 1 1 1 1 1 1 1]
8
8
2
[1 1 0 1 1 1 1 1]
8
8
4
[1 1 0 1 0 1 1 1]
8
8
3
[1 1 0 0 0 1 1 1]
